exports.continue        = 100
exports.switchProtocols = 101
exports.processing      = 102

exports.ok               = 200
exports.created          = 201
exports.accepted         = 202
exports.nonAuthoritative = 203
exports.noContent        = 204
exports.resetContent     = 205
exports.partialContent   = 206
exports.multiStatus      = 207
exports.alreadyReported  = 208
exports.imUsed           = 226

exports.multipleChoices   = 300
exports.movedPermanently  = 301
exports.found             = 302
exports.seeOther          = 303
exports.notModified       = 304
exports.useProxy          = 305
exports.switchProxy       = 306
exports.temporaryRedirect = 307
exports.permanentRedirect = 308

exports.badRequest                       = 400
exports.unauthorized                     = 401
exports.paymentRequired                  = 402
exports.forbidden                        = 403
exports.notFound                         = 404
exports.methodNotAllowed                 = 405
exports.notAcceptable                    = 406
exports.proxyAuthenticationRequired      = 407
exports.requestTimeout                   = 408
exports.conflict                         = 409
exports.gone                             = 410
exports.lengthRequired                   = 411
exports.preconditionFailed               = 412
exports.requestEntityTooLarge            = 413
exports.requestUriTooLong                = 414
exports.unsupportedMediaType             = 415
exports.requestedRangeNotSatisfiable     = 416
exports.expectationFailed                = 417
exports.imATeapot                        = 418
exports.authenticationTimeout            = 419
exports.methodFailure                    = 420
exports.enhanceYourCalm                  = 420
exports.unprocessableEntity              = 422
exports.locked                           = 423
exports.failedDependency                 = 424
exports.unorderedCollection              = 425
exports.upgradeRequired                  = 426
exports.preconditionRequired             = 428
exports.tooManyRequests                  = 429
exports.requestHeaderFieldsTooLarge      = 431
exports.loginTimeout                     = 440
exports.noResponse                       = 444
exports.retryWith                        = 449
exports.blockedByWindowsParentalControls = 450
exports.unavailableForLegalReasons       = 451
exports.requestHeaderTooLarge            = 494
exports.certError                        = 495
exports.noCert                           = 496
exports.httpToHttps                      = 497
exports.clientClosedRequest              = 499

exports.internalServerError          = 500
exports.notImplemented               = 501
exports.badGateway                   = 502
exports.serviceUnavailable           = 503
exports.gatewayTimeout               = 504
exports.httpVersionNotSupported      = 505
exports.variantAlsoNegotiates        = 506
exports.insuficientStorage           = 507
exports.loopDetected                 = 508
exports.bandwidthLimitExceeded       = 509
exports.notExtended                  = 510
exports.networkAuthenticationReuired = 511
exports.originError                  = 520
exports.webServerIsDown              = 521
exports.connectionTimedOut           = 522
exports.proxyDeclinedRequest         = 523
exports.aTimeoutOccured              = 524
exports.networkReadTimeoutError      = 598
exports.networkConnectTimeoutError   = 599

exports[100] = 'Continue'
exports[101] = 'Switch Protocols'
exports[102] = 'Processing'
exports[200] = 'OK'
exports[201] = 'Created'
exports[202] = 'Accepted'
exports[203] = 'Non-Authoritative Information'
exports[204] = 'No Content'
exports[205] = 'Reset Content'
exports[206] = 'Partial Content'
exports[207] = 'Multi-Status'
exports[208] = 'Already Reported'
exports[226] = 'IM Used'
exports[300] = 'Multiple Choices'
exports[301] = 'Moved Permanently'
exports[302] = 'Found'
exports[303] = 'Se Other'
exports[304] = 'Not Modified'
exports[305] = 'Use Proxy'
exports[306] = 'Switch Proxy'
exports[307] = 'Temporary Redirect'
exports[308] = 'Permanent Redirect'
exports[400] = 'Bad Request'
exports[401] = 'Unauthorized'
exports[402] = 'Payment Required'
exports[403] = 'Forbidden'
exports[404] = 'Not Found'
exports[405] = 'Method Not Allowed'
exports[406] = 'Not Acceptable'
exports[407] = 'Proxy Authentication Required'
exports[408] = 'Request Timeout'
exports[409] = 'Conflict'
exports[410] = 'Gone'
exports[411] = 'Length Required'
exports[412] = 'Precondition Failed'
exports[413] = 'Request Entity Too Large'
exports[414] = 'Request-URI Too Long'
exports[415] = 'Unsupported Media Type'
exports[416] = 'Requested Range Not Satisfiable'
exports[417] = 'Expectation Failed'
exports[418] = "I'm a teapot"
exports[419] = 'Authentication Timeout'
exports[422] = 'Unprocessable Entity'
exports[423] = 'Locked'
exports[424] = 'Failed Dependency'
exports[425] = 'Unordered Collection'
exports[426] = 'Upgrade Required'
exports[428] = 'Precondition Required'
exports[429] = 'Too Many Requests'
exports[431] = 'Request Header Fields Too Large'
exports[440] = 'Login Timeout'
exports[444] = 'No Response'
exports[449] = 'Retry With'
exports[450] = 'Blocked by Windows Parental Controls'
exports[451] = 'Unavailable for Legal Reasons'
exports[494] = 'Request Header Too Large'
exports[495] = 'Cert Error'
exports[496] = 'No Cert'
exports[497] = 'HTTP to HTTPS'
exports[499] = 'Client Closed Request'
exports[500] = 'Internal Server Error'
exports[501] = 'Not Implemented'
exports[502] = 'Bad Gateway'
exports[503] = 'Service Unavailable'
exports[504] = 'Gateway Timeout'
exports[505] = 'HTTP Version Not Supported'
exports[506] = 'Variant Also Negotiates'
exports[507] = 'Insufficient Storate'
exports[508] = 'Loop Detected'
exports[509] = 'Bandwidth Limit Exceeded'
exports[510] = 'Not Extended'
exports[511] = 'Network Authentication Required'
exports[520] = 'Origin Error'
exports[521] = 'Web Server is Down'
exports[522] = 'Connection Timed Out'
exports[523] = 'Proxy Declined Request'
exports[524] = 'A Timeout Occurred'
exports[598] = 'Network Read Timeout Error'
exports[599] = 'Network Connect Timeout Error'
